

luajit_old.exe -b glue.lua  glue.o
luajit_old.exe -b stddef_h.lua  stddef_h.o
luajit_old.exe -b systypes_h.lua  systypes_h.o
luajit_old.exe -b unit.lua  unit.o
luajit_old.exe -b winapi_accelerator.lua  winapi_accelerator.o
luajit_old.exe -b winapi_array.lua  winapi_array.o
luajit_old.exe -b winapi_basebuttonclass.lua  winapi_basebuttonclass.o
luajit_old.exe -b winapi_basewindowclass.lua  winapi_basewindowclass.o
luajit_old.exe -b winapi_bitmask.lua  winapi_bitmask.o
luajit_old.exe -b winapi_button.lua  winapi_button.o
luajit_old.exe -b winapi_buttonclass.lua  winapi_buttonclass.o
luajit_old.exe -b winapi_cairopanel.lua  winapi_cairopanel.o
luajit_old.exe -b winapi_cairosgpanel.lua  winapi_cairosgpanel.o
luajit_old.exe -b winapi_checkboxclass.lua  winapi_checkboxclass.o
luajit_old.exe -b winapi_class.lua  winapi_class.o
luajit_old.exe -b winapi_color.lua  winapi_color.o
luajit_old.exe -b winapi_colorchooser.lua  winapi_colorchooser.o
luajit_old.exe -b winapi_combobox.lua  winapi_combobox.o
luajit_old.exe -b winapi_comboboxclass.lua  winapi_comboboxclass.o
luajit_old.exe -b winapi_comboboxex.lua  winapi_comboboxex.o
luajit_old.exe -b winapi_comctl.lua  winapi_comctl.o
luajit_old.exe -b winapi_comdlg.lua  winapi_comdlg.o
luajit_old.exe -b winapi_controlclass.lua  winapi_controlclass.o
luajit_old.exe -b winapi_cursor.lua  winapi_cursor.o
luajit_old.exe -b winapi_debug.lua  winapi_debug.o
luajit_old.exe -b winapi_edit.lua  winapi_edit.o
luajit_old.exe -b winapi_editclass.lua  winapi_editclass.o
luajit_old.exe -b winapi_ffi.lua  winapi_ffi.o
luajit_old.exe -b winapi_filedialogs.lua  winapi_filedialogs.o
luajit_old.exe -b winapi_font.lua  winapi_font.o
luajit_old.exe -b winapi_fontex.lua  winapi_fontex.o
luajit_old.exe -b winapi_gl.lua  winapi_gl.o
luajit_old.exe -b winapi_gl11.lua  winapi_gl11.o
luajit_old.exe -b winapi_gl21.lua  winapi_gl21.o
luajit_old.exe -b winapi_groupboxclass.lua  winapi_groupboxclass.o
luajit_old.exe -b winapi_handlelist.lua  winapi_handlelist.o
luajit_old.exe -b winapi_headercontrol.lua  winapi_headercontrol.o
luajit_old.exe -b winapi_icon.lua  winapi_icon.o
luajit_old.exe -b winapi_imagelist.lua  winapi_imagelist.o
luajit_old.exe -b winapi_imagelistclass.lua  winapi_imagelistclass.o
luajit_old.exe -b winapi_init.lua  winapi_init.o
luajit_old.exe -b winapi_itemlist.lua  winapi_itemlist.o
luajit_old.exe -b winapi_listbox.lua  winapi_listbox.o
luajit_old.exe -b winapi_listboxclass.lua  winapi_listboxclass.o
luajit_old.exe -b winapi_listview.lua  winapi_listview.o
luajit_old.exe -b winapi_listviewclass.lua  winapi_listviewclass.o
luajit_old.exe -b winapi_logfonttype.lua  winapi_logfonttype.o
luajit_old.exe -b winapi_menu.lua  winapi_menu.o
luajit_old.exe -b winapi_menuclass.lua  winapi_menuclass.o
luajit_old.exe -b winapi_messagebox.lua  winapi_messagebox.o
luajit_old.exe -b winapi_messageloop.lua  winapi_messageloop.o
luajit_old.exe -b winapi_module.lua  winapi_module.o
luajit_old.exe -b winapi_namespace.lua  winapi_namespace.o
luajit_old.exe -b winapi_object.lua  winapi_object.o
luajit_old.exe -b winapi_panelclass.lua  winapi_panelclass.o
luajit_old.exe -b winapi_process.lua  winapi_process.o
luajit_old.exe -b winapi_radiobuttonclass.lua  winapi_radiobuttonclass.o
luajit_old.exe -b winapi_registry.lua  winapi_registry.o
luajit_old.exe -b winapi_resource.lua  winapi_resource.o
luajit_old.exe -b winapi_richedit.lua  winapi_richedit.o
luajit_old.exe -b winapi_rpc_types.lua  winapi_rpc_types.o
luajit_old.exe -b winapi_shellapi.lua  winapi_shellapi.o
luajit_old.exe -b winapi_showcase.lua  winapi_showcase.o
luajit_old.exe -b winapi_spi.lua  winapi_spi.o
luajit_old.exe -b winapi_static.lua  winapi_static.o
luajit_old.exe -b winapi_struct.lua  winapi_struct.o
luajit_old.exe -b winapi_sysinfo.lua  winapi_sysinfo.o
luajit_old.exe -b winapi_tabcontrol.lua  winapi_tabcontrol.o
luajit_old.exe -b winapi_tabcontrolclass.lua  winapi_tabcontrolclass.o
luajit_old.exe -b winapi_toolbar.lua  winapi_toolbar.o
luajit_old.exe -b winapi_toolbarclass.lua  winapi_toolbarclass.o
luajit_old.exe -b winapi_tooltip.lua  winapi_tooltip.o
luajit_old.exe -b winapi_treeview.lua  winapi_treeview.o
luajit_old.exe -b winapi_types.lua  winapi_types.o
luajit_old.exe -b winapi_util.lua  winapi_util.o
luajit_old.exe -b winapi_uuid.lua  winapi_uuid.o
luajit_old.exe -b winapi_vkcodes.lua  winapi_vkcodes.o
luajit_old.exe -b winapi_vobject.lua  winapi_vobject.o
luajit_old.exe -b winapi_waitemlistclass.lua  winapi_waitemlistclass.o
luajit_old.exe -b winapi_wcs.lua  winapi_wcs.o
luajit_old.exe -b winapi_wgl.lua  winapi_wgl.o
luajit_old.exe -b winapi_wglext.lua  winapi_wglext.o
luajit_old.exe -b winapi_wglpanel.lua  winapi_wglpanel.o
luajit_old.exe -b winapi_wglpanel_demo.lua  winapi_wglpanel_demo.o
luajit_old.exe -b winapi_window.lua  winapi_window.o
luajit_old.exe -b winapi_windowclass.lua  winapi_windowclass.o
luajit_old.exe -b winapi_windowclasses.lua  winapi_windowclasses.o
luajit_old.exe -b winapi_windowmessages.lua  winapi_windowmessages.o
luajit_old.exe -b winapi_wingdi.lua  winapi_wingdi.o
luajit_old.exe -b winapi_winnt.lua  winapi_winnt.o
luajit_old.exe -b winapi_wintypes.lua  winapi_wintypes.o
luajit_old.exe -b winapi_winuser.lua  winapi_winuser.o
luajit_old.exe -b winapi_winusertypes.lua  winapi_winusertypes.o
msvcbuild static
